name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Github Action
      uses: actions/checkout@v4
    
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Inventory Image
      run: |
        IMAGE_TAG=ghcr.io/leds-org/managementjob:$(date +%s)
        docker build . --tag $IMAGE_TAG
        docker push $IMAGE_TAG
